// Prompt pool organised by category.
// Each entry maps to a row in the `prompts` table.
// Categories must match the values used in the frontend category picker.

const SEED_PROMPTS = [
  // ── Branding ─────────────────────────────────────────────────────────────
  {
    category: 'Branding',
    project_name: 'Arctic Roast Coffee',
    type: 'Brand Identity',
    objective: 'Create a cohesive brand identity for a premium cold brew brand targeting outdoor enthusiasts',
    background: 'New D2C cold brew brand positioning itself as "adventurous and crisp." Sells through outdoor gear shops and a Shopify store.',
    target_audience: 'Outdoor enthusiasts and athletes ages 22–35 who want bold, on-the-go caffeine',
    key_message: 'Cold. Bold. Untamed.',
    call_to_action: 'Find us at your local outdoor gear shop',
    visual_direction: 'Deep navy, ice-white, and glacier blue. Rugged yet clean. No gradients — flat and bold.',
  },
  {
    category: 'Branding',
    project_name: 'Solstice Skincare',
    type: 'Brand Identity',
    objective: 'Develop brand visuals for a clean beauty line launching its first SPF product',
    background: 'Eco-conscious skincare startup pivoting to sustainable packaging. SPF 50 sunscreen is the hero launch item for summer.',
    target_audience: 'Women ages 25–40 who prioritize clean, reef-safe ingredients and sustainable packaging',
    key_message: 'Sun-proof. Earth-approved.',
    call_to_action: 'Shop the full collection online',
    visual_direction: 'Natural and premium. Sandy beiges, sun-bleached whites, earthy terracotta. Organic shapes, no hard edges.',
  },
  {
    category: 'Branding',
    project_name: 'Pulse Fitness',
    type: 'Brand Identity',
    objective: 'Design a brand system for a boutique HIIT gym that feels energetic but not intimidating',
    background: 'A new boutique gym in a mid-size city competing with big-box gyms by emphasising community and programming quality.',
    target_audience: 'Adults ages 25–45 who want structured group fitness without the ego of a traditional gym',
    key_message: 'Train harder. Feel better. Together.',
    call_to_action: 'Book your first class free',
    visual_direction: 'Electric red, black, and white. Dynamic and angular. Feels like movement. Avoid stock-photo clichés.',
  },

  // ── UI Design ─────────────────────────────────────────────────────────────
  {
    category: 'UI Design',
    project_name: 'Bloom Wellness',
    type: 'Mobile App Screen',
    objective: 'Design an onboarding screen for a mental wellness app that communicates calm and builds immediate trust',
    background: 'A wellness startup targeting remote-worker burnout. Offers guided meditation and mood journaling. 4-screen onboarding flow; this is screen 1.',
    target_audience: 'Remote workers ages 25–40 experiencing stress or burnout',
    key_message: 'Your peace starts here.',
    call_to_action: 'Start your free 7-day trial',
    visual_direction: 'Soft gradients, rounded shapes, muted greens and lavender. Warm and inviting. Never clinical.',
  },
  {
    category: 'UI Design',
    project_name: 'Vault Password Manager',
    type: 'Dashboard Screen',
    objective: 'Design a credential dashboard that makes stored logins feel secure and easy to manage',
    background: 'B2C password manager targeting non-technical users who find existing tools intimidating. 10k users, launched 6 months ago.',
    target_audience: 'Non-technical adults ages 30–55 managing 20+ passwords across work and personal accounts',
    key_message: 'Security made simple.',
    call_to_action: 'Try Vault free for 30 days',
    visual_direction: 'Clean and trustworthy. Deep blues and white space. Subtle lock iconography. Zero clutter.',
  },
  {
    category: 'UI Design',
    project_name: 'Orbit Task Manager',
    type: 'Mobile App Screen',
    objective: 'Design a today-view task screen that makes prioritisation feel effortless',
    background: 'Productivity app aimed at freelancers who juggle multiple clients. Differentiator is an AI that auto-prioritises tasks by deadline and energy level.',
    target_audience: 'Freelancers and independent contractors ages 22–38',
    key_message: 'Less chaos. More done.',
    call_to_action: 'Download free on the App Store',
    visual_direction: 'Monochrome base with a single accent colour per project. Dense but airy. Think Notion meets Things 3.',
  },

  // ── Illustration ──────────────────────────────────────────────────────────
  {
    category: 'Illustration',
    project_name: 'Pip and the Dark',
    type: "Children's Book Cover",
    objective: "Illustrate a cover for a children's bedtime story about a dragon who is afraid of the dark",
    background: "Self-published picture book for ages 3–7. Warm, funny, and reassuring in tone. The dragon is named Pip and is small, round, and purple.",
    target_audience: 'Children ages 3–7 and the parents reading to them',
    key_message: 'Even dragons need a nightlight.',
    call_to_action: 'Available at independent bookstores nationwide',
    visual_direction: 'Cosy and whimsical. Deep purples, warm golds, soft glowing light. A small flame for comfort.',
  },
  {
    category: 'Illustration',
    project_name: 'Coastal Spirits Brewery',
    type: 'Label Illustration',
    objective: 'Create a narrative illustration for a craft beer label inspired by Pacific Northwest folklore',
    background: 'Small-batch brewery releasing a seasonal stout called "Tidewalker." Story involves a sea creature that guides lost ships home.',
    target_audience: 'Craft beer enthusiasts ages 25–45 who appreciate artisan storytelling',
    key_message: 'Every sip tells a story.',
    call_to_action: 'Find Tidewalker at select bottle shops this November',
    visual_direction: 'Dark, moody, and textured. Deep teals and ink blacks with a single warm highlight. Etching or woodblock aesthetic.',
  },
  {
    category: 'Illustration',
    project_name: 'Wanderlust Travel Poster',
    type: 'Travel Poster',
    objective: 'Design a retro-style travel poster for Kyoto, Japan aimed at a modern audience',
    background: 'A travel agency is launching a limited print series of illustrated destination posters. Kyoto is the first in the series.',
    target_audience: 'Design-conscious travellers ages 28–45 who collect art prints',
    key_message: 'Kyoto — where every path is a poem.',
    call_to_action: 'Limited prints available at wanderlust.co',
    visual_direction: 'Mid-century modern travel poster aesthetic. Flat shapes, limited palette (cherry blossom pink, ink black, cream, gold). No photos.',
  },

  // ── Typography ────────────────────────────────────────────────────────────
  {
    category: 'Typography',
    project_name: 'Velvet Jazz Festival',
    type: 'Event Typographic Poster',
    objective: 'Design a typographic poster for a jazz festival where the type itself carries the mood',
    background: 'An annual jazz festival in New Orleans celebrating its 10th year. Headline act: a fusion trio mixing jazz, soul, and electronic. No photos allowed — type only.',
    target_audience: 'Jazz and live music fans ages 28–55',
    key_message: 'Ten years of sound. One night of magic.',
    call_to_action: 'Tickets at velverjazz.com',
    visual_direction: 'Expressive and moody. Deep burgundy and gold. Mix display type scales. Think Blue Note Records.',
  },
  {
    category: 'Typography',
    project_name: 'The Founders Manifesto',
    type: 'Editorial Spread',
    objective: 'Lay out a one-page editorial spread for a startup manifesto using typography as the primary design element',
    background: 'A VC firm publishes an annual print magazine. This year\'s opening spread is a bold manifesto about the role of design in startups. 300 words of copy provided.',
    target_audience: 'Founders, designers, and investors ages 25–45',
    key_message: 'Design is not decoration. It is decision-making.',
    call_to_action: 'Read the full issue at foundersreview.co',
    visual_direction: 'Editorial and authoritative. Black and white with one accent. Large contrast in type sizes. Grid-based structure.',
  },
  {
    category: 'Typography',
    project_name: 'Botanica Restaurant',
    type: 'Menu Design',
    objective: 'Design a single-page dinner menu that reflects the restaurant\'s farm-to-table identity through typography alone',
    background: 'An upscale farm-to-table restaurant in Portland. Seasonal menu changes weekly. The owner wants the menu to feel like a handwritten letter, but elevated.',
    target_audience: 'Diners ages 30–55 who value craft and provenance',
    key_message: 'Grown here. Made here. Served here.',
    call_to_action: 'Reserve your table at botanica-pdx.com',
    visual_direction: 'Organic and refined. Cream paper texture, dark ink. Mix of serif and handwritten type. Generous white space.',
  },

  // ── Logo Design ───────────────────────────────────────────────────────────
  {
    category: 'Logo Design',
    project_name: 'Nova Music Festival',
    type: 'Logo & Wordmark',
    objective: 'Design a logo and wordmark for a boutique indie music festival entering its second year',
    background: 'Boutique festival that sold out in 48 hours last year. Lineup features 20 emerging indie and alternative artists across 3 days.',
    target_audience: 'Music fans ages 18–30 who prefer indie and alternative genres',
    key_message: 'Three days. Twenty artists. One unforgettable weekend.',
    call_to_action: 'Grab your early-bird pass at novafest.com',
    visual_direction: 'Retro 70s influence with a modern edge. Warm oranges and dusty pinks. Mark should work in one colour.',
  },
  {
    category: 'Logo Design',
    project_name: 'GreenPath',
    type: 'Non-profit Logo',
    objective: 'Design a logo for an environmental NGO that runs urban reforestation programmes',
    background: 'Community-funded NGO operating in 8 cities. Plants trees in urban areas and runs school education programmes. Needs a mark that works on T-shirts, signage, and digital.',
    target_audience: 'Eco-conscious community members, donors, and school partners',
    key_message: 'Replant. Restore. Rethink.',
    call_to_action: 'Join the movement at greenpath.org',
    visual_direction: 'Hopeful and grounded. Forest greens and earth tones. Simple geometric mark. Must be legible at 16px.',
  },
  {
    category: 'Logo Design',
    project_name: 'Apex Esports',
    type: 'Esports Team Logo',
    objective: 'Design a competitive esports team logo that commands respect on the main stage',
    background: 'Semi-professional esports team competing in regional FPS tournaments. Team of 5, based in Austin. Looking for a mark that can go on jerseys, overlays, and merch.',
    target_audience: 'Esports fans and competitors ages 16–28',
    key_message: 'Compete without limits.',
    call_to_action: 'Follow @ApexEsports for match updates',
    visual_direction: 'Bold and aggressive. Dark backgrounds with electric accents (cyan or orange). Symmetrical mark preferred. No generic "shield + sword" clichés.',
  },

  // ── Web Design ────────────────────────────────────────────────────────────
  {
    category: 'Web Design',
    project_name: 'UrbanGrid E-Scooter',
    type: 'Landing Page Hero',
    objective: 'Design a hero section for a city e-scooter rental service that drives app downloads',
    background: 'Urban mobility startup launching in 5 cities. Competing on affordability and sustainability. Target is 10k downloads in the first month.',
    target_audience: 'Urban commuters ages 20–35 who want eco-friendly last-mile transport',
    key_message: 'Skip the traffic. Ride smarter.',
    call_to_action: 'Unlock your first ride free',
    visual_direction: 'Electric green and charcoal. Fast and minimal. Motion-inspired — convey speed without being chaotic.',
  },
  {
    category: 'Web Design',
    project_name: 'TechFest 2026',
    type: 'Event Landing Page',
    objective: 'Design a landing page for an annual student hackathon that drives ticket registrations',
    background: 'Annual student hackathon at a major university. 500 attendees expected. Sponsors include Google and Anthropic. Previous year sold out.',
    target_audience: 'College students ages 18–24 interested in startups, design, and engineering',
    key_message: 'Build. Pitch. Win.',
    call_to_action: 'Register before spots fill up',
    visual_direction: 'Bold and high-energy. Dark background with neon accents. Think hackathon energy, not corporate conference.',
  },
  {
    category: 'Web Design',
    project_name: 'FreshPlate',
    type: 'Homepage Design',
    objective: 'Design a homepage for a meal-kit delivery service that makes healthy eating feel achievable',
    background: 'Meal-kit startup competing with HelloFresh and Blue Apron by focusing on 15-minute recipes for busy families. Subscription-based.',
    target_audience: 'Parents and busy professionals ages 28–45 who want home-cooked meals without the planning',
    key_message: 'Real food. Real fast.',
    call_to_action: 'Get your first box for $9.99',
    visual_direction: 'Fresh and appetising. Bright greens, warm whites, food photography as hero. Clean grid layout.',
  },
]

module.exports = SEED_PROMPTS
